name: run revenue_with_categories

on: 
    #Uncomment for Manual workflow 
    [workflow_dispatch]
  # schedule:
  #   - cron: '0 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    # Need to specify environment if we want to use environment secrets
    environment: SERVER
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      
      - name: install ODBC driver 
        run:
            |
            sudo apt-get update \
            && sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 \
            && sudo apt-get install -y unixodbc-dev
            # sudo apt-get install -y unixodbc-dev \
            # && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
            # && curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list > /etc/apt/sources.list.d/mssql-release.list \
            # && sudo apt-get update \
            # && sudo ACCEPT_EULA=Y apt-get -q -y install msodbcsql17 \
            # sudo apt-get update \
            # && sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 -y\
            # && sudo apt-get install unixodbc-dev -y
        shell: sudo bash {0} 

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
          SERVER: ${{ secrets.SERVER }}
          DB: ${{ secrets.DB }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python project/merck_revenue_with_categories_V2.py
          
      - name: commit files
        run: |
          git config --local user.email "t.lakkhananukun@gmail.com"
          git config --local user.name "chatchawan90"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated categories" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token  }}
          branch: main 
